Setup FPGA script
chipsalliance/caliptra-sw pull request #1099
Opened 2023-11-21 09:41 UTC by leongross

If one works with the hardware FPGA some sysfs configurations and kernel module loads have to be performed after each reboot.

This script performs all the required setup and adds some sanity checks.

2023-11-24 08:53 UTC, MDr164 reviewed
Can you add a short note in this PR to the FPGA instructions that this script exists? https://github.com/chipsalliance/caliptra-sw/blob/main/hw-latest/fpga/FPGA_Instructions.md

2023-11-28 00:03 UTC, jhand2 approved these changes

2023-11-28 00:03 UTC, jhand2 commented on setup_fpga.sh
> +# entryppoint
sp: entrypoint

2023-12-04 22:36 UTC, jlmahowa-amd requested changes
Thanks for doing this, and sorry for being slow on review.

2023-12-11 15:50 UTC, MDr164 approved these changes

2023-12-11 15:53 UTC, leongross commented
@jlmahowa-amd is your change request satisfied? If so, please resolve it so we can merge this.

2024-01-05 09:49 UTC, leongross commented
@jlmahowa-amd

2024-01-09 17:06 UTC, jlmahowa-amd submitted a review, later dismissed

2024-01-12 18:52 UTC, jhand2 approved these changes

2024-01-16 18:24 UTC, jlmahowa-amd requested changes
Something went wrong and this no longer reflects the fixes and changes I last reviewed.

2024-01-30 18:30 UTC, jlmahowa-amd commented
I pushed a branch with the version of the PR that I tested and approved. Please take a look to see the difference.
https://github.com/chipsalliance/caliptra-sw/compare/main...jlmahowa/fpga_setup

2024-03-05 21:37 UTC, jlmahowa-amd commented
These changes were brought in as part of #1270

2024-03-05 21:37 UTC, closed without merging

2024-03-06 10:04 UTC, leongross commented
Looks good, thank you for taking care of that. Please excuse the low responsiveness on this.