Added Support For Update Reset Flow
chipsalliance/caliptra-sw pull request #120
Opened 2023-03-30 07:26 UTC by ajisaxena

This commit adds the support for update reset flow. Modifications to the verifier to check the reset reason and perform additional checks for the image being downloaded.

2023-03-31 23:00 UTC, mhatrevi commented on image/verify/src/lib.rs
> +    fn own_pub_key_digest_dv(&self) -> ImageDigest;
NIT: Spell out owner

2023-03-31 23:00 UTC, mhatrevi commented on image/verify/src/verifier.rs
> +        UpdateResetOwnerDigestFailure=29,
NIT: Spacing.

2023-03-31 23:05 UTC, mhatrevi commented on rom/dev/src/flow/update_reset.rs
> +        MailboxAccessFailure=0x04,
NIT: Inconsistent spacing.

2023-03-31 23:07 UTC, mhatrevi commented on rom/dev/src/flow/update_reset.rs
> +        InavalidFirmwareCommand=0x03,
Spelling: Invalid

2023-03-31 23:19 UTC, mhatrevi commented on rom/dev/src/flow/update_reset.rs
> +        dst.clone_from_slice(src);
Old and new firmware sizes could be different.

2023-03-31 23:25 UTC, mhatrevi commented on rom/dev/src/verifier.rs
> +    // Save the fmc digest in the data vault on cold boot
Get

2023-03-31 23:27 UTC, mhatrevi requested changes
Added few comments to the PR; please take a look.

2023-04-14 00:57 UTC, vsonims approved these changes

2023-04-14 00:57 UTC, mhatrevi approved these changes

2023-04-14 00:57 UTC, merged