Add support for the DMA widget
chipsalliance/caliptra-sw pull request #1692
Opened 2024-09-27 20:39 UTC by ArthurHeymans

2024-10-03 16:23 UTC, swenson approved these changes
LGTM. Would be nice to get some clarity on those TODOs, but this looks good for now to unblock us.

2024-10-04 16:18 UTC, mhatrevi requested changes

2024-10-04 16:30 UTC, mhatrevi commented on sw-emulator/app/src/main.rs
> +        .arg(
Can do something simple like recovery-image-fw / recovery-image-manifest, recovery-image-mcurt as param names.

2024-10-08 15:52 UTC, mhatrevi commented on sw-emulator/app/src/main.rs
>      let args_current_fw = args.get_one::<PathBuf>("firmware");
let args_current_fw = args.get_one::<PathBuf>("firmware"); 

This should be removed as recovery-image-fw is the firmware. Also, rename the update-firmware to recover-image-fw-update

2024-10-10 03:08 UTC, mhatrevi approved these changes

2024-10-10 16:35 UTC, swenson approved these changes
LGTM

2024-10-10 18:25 UTC, merged