Adding the stash measurement functionality to AuthorizeAndStashCmd
chipsalliance/caliptra-sw pull request #1763
Opened 2024-11-01 15:32 UTC by mhatrevi

2024-11-01 16:33 UTC, swenson submitted a review, later dismissed
LGTM

2024-11-01 17:58 UTC, jhand2 requested changes
This is the same as https://github.com/chipsalliance/caliptra-sw/pull/1752. Can we chery-pick that commit instead of creating a new one?

2024-11-01 17:58 UTC, jhand2 commented on runtime/src/authorize_and_stash.rs
> +                // TODO do we need to return this?
nit: remove TODO

2024-11-02 00:15 UTC, mhatrevi commented on runtime/src/authorize_and_stash.rs
> +                // TODO do we need to return this?
Removed.

2024-11-04 21:02 UTC, jhand2 approved these changes

2024-11-04 21:02 UTC, merged