Increase runtime stack size to 64KiB
chipsalliance/caliptra-sw pull request #1784
Opened 2024-11-12 22:41 UTC by clundin25

2024-11-12 23:41 UTC, jhand2 approved these changes

2024-11-13 18:13 UTC, MDr164 approved these changes

2024-11-13 21:30 UTC, mhatrevi requested changes
What is the motivation for this much increase in stack size? Reducing the DATA_SIZE to 22 K will be insufficient for storing Caliptra 2.0 MLDSA related artifacts (TBSes, public keys, signatures etc)

2024-11-13 22:05 UTC, clundin25 commented
> What is the motivation for this much increase in stack size? Reducing the DATA_SIZE to 22 K will be insufficient for storing Caliptra 2.0 MLDSA related artifacts (TBSes, public keys, signatures etc)

The current maximum observed stack usage is ~54,208 bytes. 

After this series of PRs is merged, I will add https://github.com/chipsalliance/caliptra-sw/pull/1785 to prevent increases in stack usage.

With that in place we can work on reducing the stack usage. I think 48KiB can be obtainable relatively quickly.

2024-11-13 22:25 UTC, jhand2 commented
> What is the motivation for this much increase in stack size? Reducing the DATA_SIZE to 22 K will be insufficient for storing Caliptra 2.0 MLDSA related artifacts (TBSes, public keys, signatures etc)

This is more of a reflection of reality than an actual increase. But ya, as Carl said, we will continue work to reduce stack usage.

2024-11-14 00:08 UTC, mhatrevi approved these changes

2024-11-14 00:58 UTC, merged