Deprecate FMC SVN from build tooling and firmware.
chipsalliance/caliptra-sw pull request #1825
Opened 2024-11-27 23:03 UTC by bluegate010

There are no functional changes in this commit.

- The reported FMC SVN is now accurately renamed to be the cold-boot firmware SVN.
- As the ROM now ignores the FMC SVN in images, build tooling longer allows populating the FMC image's SVN.

2024-12-23 19:23 UTC, jhand2 commented on error/src/lib.rs
> +    // 0x000b002d was IMAGE_VERIFIER_ERR_FIRMWARE_SVN_LESS_THAN_MIN_SUPPORTED
nit: it would be helpful for the comments to explicitly say `Deprecated`

2024-12-23 19:23 UTC, jhand2 commented on image/gen/src/generator.rs
> +            svn,
I thought we moved the SVN to a different part of the header. Should the svn field in the individual image entries be deprecated?

2025-01-22 05:10 UTC, mhatrevi commented on api/src/soc_mgr.rs
> +        self.soc_ifc().fuse_fmc_key_manifest_svn().write(|_| 0); // deprecated fuse.
Is there a need to set this?

2025-01-22 05:12 UTC, mhatrevi commented on drivers/src/fuse_bank.rs
> +        // The legacy name of this register is `fuse_runtime_svn`
Can we file an RTL  issue to rename this fuse to fuse_fw_snv?

2025-01-22 05:13 UTC, mhatrevi commented on api/src/soc_mgr.rs
> +        self.soc_ifc().fuse_fmc_key_manifest_svn().write(|_| 0); // deprecated fuse.
Also, can we file a RTL issue to remove the FMC svn?

2025-01-22 05:15 UTC, mhatrevi commented on hw-model/c-binding/examples/api/caliptra_api.c
> +    caliptra_fuse_write(model, GENERIC_AND_FUSE_REG_FUSE_FMC_KEY_MANIFEST_SVN, 0); // FMC SVN deprecated
Is writing to the deprecated FMC svn needed?

2025-01-22 05:24 UTC, mhatrevi commented on image/gen/src/generator.rs
> +            svn,
Let's remove the svn from ImageTocEntry and add it to ImageManifest. We can place it before the ImagePreamble.

2025-01-22 05:25 UTC, mhatrevi commented on libcaliptra/src/caliptra_api.c
> +    caliptra_generic_and_fuse_write(GENERIC_AND_FUSE_REG_FUSE_FMC_KEY_MANIFEST_SVN, 0); // Deprecated fuse.
Is this needed?

2025-01-22 05:27 UTC, mhatrevi requested changes
Please see the feedback.

2025-01-25 02:39 UTC, bluegate010 commented on error/src/lib.rs
> +    // 0x000b002d was IMAGE_VERIFIER_ERR_FIRMWARE_SVN_LESS_THAN_MIN_SUPPORTED
Done.

2025-01-25 02:41 UTC, bluegate010 commented on api/src/soc_mgr.rs
> +        self.soc_ifc().fuse_fmc_key_manifest_svn().write(|_| 0); // deprecated fuse.
Removed. And we have https://github.com/chipsalliance/caliptra-rtl/issues/159.

2025-01-25 02:42 UTC, bluegate010 commented on drivers/src/fuse_bank.rs
> +        // The legacy name of this register is `fuse_runtime_svn`
In https://github.com/chipsalliance/caliptra-rtl/issues/159#issuecomment-2256655215 Bharat suggested we edit the spec and let that bubble into the RTL. Am doing so in https://github.com/chipsalliance/Caliptra/pull/262.

2025-01-25 02:42 UTC, bluegate010 commented on hw-model/c-binding/examples/api/caliptra_api.c
> +    caliptra_fuse_write(model, GENERIC_AND_FUSE_REG_FUSE_FMC_KEY_MANIFEST_SVN, 0); // FMC SVN deprecated
Removed.

2025-01-25 02:43 UTC, bluegate010 commented on libcaliptra/src/caliptra_api.c
> +    caliptra_generic_and_fuse_write(GENERIC_AND_FUSE_REG_FUSE_FMC_KEY_MANIFEST_SVN, 0); // Deprecated fuse.
Removed.

2025-01-27 03:57 UTC, bluegate010 commented on image/gen/src/generator.rs
> +            svn,
Moving the SVN in https://github.com/chipsalliance/caliptra-sw/pull/1909. I put it in the ImageHeader instead of ImageManifest, because only certain fields of the manifest are covered by signature.

2025-02-03 16:46 UTC, mhatrevi approved these changes

2025-02-03 16:46 UTC, merged