Fix driver/dma: Operate on 64bit addresses
chipsalliance/caliptra-sw pull request #1861
Opened 2024-12-18 07:41 UTC by ArthurHeymans

This fixes the driver side to operate on 64bit AXI addresses.

Currently the sw-emulator DMA engine operates on the root_bus which is 32bit.
Is that 32bit root bus that caliptra has access to a subset of the 64bit AXI bus which only the DMA engine has full access to?

2024-12-18 19:56 UTC, swenson reviewed
AXI is a separate bus from the main memory bus. Importantly, AXI does *NOT* have access to the main memory bus or DCCM in any way.

Instead, AXI maps specific addresses to external peripherals (and maybe to their RAM as well).

This code seems okay for the driver, but we might need to rethink how the emulator works.

2024-12-18 19:56 UTC, swenson commented on drivers/src/lib.rs
> +pub use dma::{AxiAddr Dma, DmaReadTarget, DmaReadTransaction, DmaWriteOrigin, DmaWriteTransaction};
I think this is a typo.

2024-12-18 22:59 UTC, mhatrevi requested changes

2024-12-18 22:59 UTC, mhatrevi commented on drivers/src/dma.rs
> +        dma.src_addr_h().write(|_| read_addr.lo);
The addresses are swapped.

2024-12-18 22:59 UTC, mhatrevi commented on drivers/src/lib.rs
> +pub use dma::{AxiAddr Dma, DmaReadTarget, DmaReadTransaction, DmaWriteOrigin, DmaWriteTransaction};
How is this even compiling?

2024-12-19 02:13 UTC, mhatrevi approved these changes

2024-12-19 02:14 UTC, mhatrevi commented on drivers/src/lib.rs
> +pub use dma::{AxiAddr Dma, DmaReadTarget, DmaReadTransaction, DmaWriteOrigin, DmaWriteTransaction};
Updated.

2024-12-19 02:25 UTC, merged