Self Signed FMC Alias Csr
chipsalliance/caliptra-sw pull request #1863
Opened 2024-12-19 15:45 UTC by rusty1968

- FMC modfied to generate a  self signed FMC Alias CSR test upon cold boot.
- Persistent driver modified to add persistent memory for the FMC Alias CSR
- Runtime modified to expose an API to retrieve it.
- Test case created to verify the self signed FMC Alias CSR.
- Test case created to verify the RT Alias Certificate with the pub key of the FMC Alias CSR.

2024-12-19 19:13 UTC, clundin25 commented on api/src/mailbox.rs
> +// GET_IDEVID_CSR
nit: Minor copy paste error

2024-12-19 19:18 UTC, clundin25 commented on drivers/src/persistent.rs
> +    reserved11: [u8; memory_layout::FMC_ALIAS_CSR_SIZE as usize - size_of::<FmcAliasCsr>()],
When the `fmc` is not enabled, a slice of `memory_layout::FMC_ALIAS_CSR_SIZE` should still be reserved so `PersistentData` is the same size / shape between image types.

2024-12-19 19:19 UTC, clundin25 commented on error/src/lib.rs
> +        CaliptraError::new_const(0x000E0053);
`0x000E0053` => `0x000E0054` so `RUNTIME_GET_FMC_CSR_UNPROVISIONED` has a unique error code.

2024-12-19 19:21 UTC, clundin25 commented on fmc/src/flow/crypto.rs
> +    /// * `priv_key` - Key slot to retrieve the private key
Looks like `pub_key` is missing from the doc comment.

2024-12-19 19:22 UTC, clundin25 commented on fmc/src/flow/fmc_alias_csr.rs
> +/// * `DiceInput` - DICE Layer Input
Looks like the doc string doesn't match the function signature.

2024-12-19 19:24 UTC, clundin25 commented on runtime/src/get_fmc_alias_csr.rs
> +            FmcAliasCsr::UNPROVISIONED_CSR => Err(CaliptraError::RUNTIME_GET_FMC_CSR_UNPROVISIONED),
Does the `0` case matter? E.g. for FMC images that did not support this feature?

2024-12-19 19:24 UTC, clundin25 commented on runtime/src/get_fmc_alias_csr.rs
> +    //   #[cfg_attr(not(feature = "no-cfi"), cfi_impl_fn)]
nit: Commented code

2024-12-19 19:25 UTC, clundin25 commented on runtime/src/get_fmc_alias_csr.rs
> +                // size of the buffer in `GetIdevCsrResp`
nit: Copy and paste mismatch

2024-12-20 01:01 UTC, jhand2 commented on common/src/lib.rs
> -pub const FMC_SIZE: u32 = 20 * 1024;
According to the size-history CI job, we're still only using ~18KiB in FMC. Do we need to change the size here?

2024-12-20 01:03 UTC, jhand2 commented on drivers/src/memory_layout.rs
> -pub const DATA_SIZE: u32 = 27 * 1024;
nit: now that https://github.com/chipsalliance/caliptra-sw/pull/1722 is merged, should be able to just add to the PersistentData driver and leave memory layout as-is

2024-12-20 01:04 UTC, jhand2 commented on drivers/src/persistent.rs
> +    pub fmc_alias_csr: FmcAliasCsr,
Doesn't this also need to be accessible in RT?

2024-12-20 01:05 UTC, jhand2 commented on runtime/src/main.rs
> +const BANNER: &str = r#"Caliptra RT"#;
optional: might be good to put size optimizations in a separate PR

2025-01-01 21:49 UTC, rusty1968 commented on api/src/mailbox.rs
> +// GET_IDEVID_CSR
Corrected. Thank you.

2025-01-02 03:11 UTC, rusty1968 commented on drivers/src/persistent.rs
> +    reserved11: [u8; memory_layout::FMC_ALIAS_CSR_SIZE as usize - size_of::<FmcAliasCsr>()],
Corrected. Thanks.

2025-01-02 03:13 UTC, rusty1968 commented on drivers/src/persistent.rs
> +    pub fmc_alias_csr: FmcAliasCsr,
Correct. The feature  is now renamed to fmc-alias-csr.

2025-01-02 03:14 UTC, rusty1968 commented on drivers/src/memory_layout.rs
> -pub const DATA_SIZE: u32 = 27 * 1024;
Agree. Thanks for pointing this out.

2025-01-02 11:07 UTC, rusty1968 commented on runtime/src/get_fmc_alias_csr.rs
> +    //   #[cfg_attr(not(feature = "no-cfi"), cfi_impl_fn)]
Thanks.

2025-01-02 11:50 UTC, rusty1968 commented on runtime/src/get_fmc_alias_csr.rs
> +            FmcAliasCsr::UNPROVISIONED_CSR => Err(CaliptraError::RUNTIME_GET_FMC_CSR_UNPROVISIONED),
It does. Thanks.

2025-01-02 11:52 UTC, rusty1968 commented on fmc/src/flow/crypto.rs
> +    /// * `priv_key` - Key slot to retrieve the private key
It was. Thanks.

2025-01-02 11:59 UTC, rusty1968 commented on error/src/lib.rs
> +        CaliptraError::new_const(0x000E0053);
Corrected, Thanks.

2025-01-02 12:14 UTC, rusty1968 commented on fmc/src/flow/fmc_alias_csr.rs
> +/// * `DiceInput` - DICE Layer Input
It did not. Thanks.

2025-01-02 12:24 UTC, rusty1968 commented on runtime/src/get_fmc_alias_csr.rs
> +                // size of the buffer in `GetIdevCsrResp`
Thanks

2025-01-02 12:33 UTC, rusty1968 commented on common/src/lib.rs
> -pub const FMC_SIZE: u32 = 20 * 1024;
I had to increase it. If I keep it the same it won't fit: 
rust-lld: error: section '.rodata' will not fit in region 'ICCM': overflowed by 312 bytes
          rust-lld: error: section '.rodata' will not fit in region 'ICCM': overflowed by 961 bytes
          rust-lld: error: section '.rodata' will not fit in region 'ICCM': overflowed by 964 bytes
          rust-lld: error: section '.rodata' will not fit in region 'ICCM': overflowed by 976 bytes
          rust-lld: error: section '.rodata' will not fit in region 'ICCM': overflowed by 988 bytes
          rust-lld: error: section '.rodata' will not fit in region 'ICCM': overflowed by 988 bytes

2025-01-09 21:29 UTC, mhatrevi commented on common/src/lib.rs
> +pub const RUNTIME_SIZE: u32 = 96 * 1024;
Why is this decreasing?

2025-01-09 21:50 UTC, mhatrevi commented on drivers/src/persistent.rs
>              );
Please re-add the check for reserved_memory.

2025-01-09 21:53 UTC, mhatrevi commented on drivers/Cargo.toml
> +fmc-alias-csr = []
Why is there a need for a separate feature for this?

2025-01-09 21:55 UTC, mhatrevi commented on fmc/src/flow/fmc_alias_csr.rs
> +fn write_csr_to_peristent_storage(env: &mut FmcEnv, csr: &FmcAliasCsr) -> CaliptraResult<()> {
This function can never fail so no point in keeping the return type as CaliptraResult.

2025-01-09 21:58 UTC, mhatrevi commented on fmc/src/flow/rt_alias.rs
>      pub fn run(env: &mut FmcEnv) -> CaliptraResult<()> {
Any particular reason for removing these?

2025-01-09 22:02 UTC, mhatrevi commented on runtime/src/main.rs
> +const BANNER: &str = r#"Caliptra RT"#;
+1

2025-01-09 22:03 UTC, mhatrevi commented on x509/src/fmc_alias_csr.rs
> +    Initial Device ID Certificate Signing Request related code.
Leftover copied comment.

2025-01-09 22:03 UTC, mhatrevi commented on x509/src/fmc_alias_csr.rs
> +    idevid_csr.rs
Leftover copied comment.

2025-01-09 22:05 UTC, mhatrevi requested changes
Please see the feedback.

2025-01-09 22:07 UTC, mhatrevi commented on drivers/src/persistent.rs
> +    pub fmc_alias_csr: FmcAliasCsr,
Why do we need a new feature for this? Can you simply use the runtime feature?

2025-01-10 19:29 UTC, rusty1968 commented on fmc/src/flow/fmc_alias_csr.rs
> +fn write_csr_to_peristent_storage(env: &mut FmcEnv, csr: &FmcAliasCsr) -> CaliptraResult<()> {
Agree. Same applies to https://github.com/chipsalliance/caliptra-sw/blob/main/rom/dev/src/flow/cold_reset/idev_id.rs#L294 ?

2025-01-10 22:28 UTC, rusty1968 commented on fmc/src/flow/rt_alias.rs
>      pub fn run(env: &mut FmcEnv) -> CaliptraResult<()> {
Saving space.

2025-01-10 22:50 UTC, rusty1968 commented on x509/src/fmc_alias_csr.rs
> +    Initial Device ID Certificate Signing Request related code.
fixed

2025-01-10 22:51 UTC, rusty1968 commented on x509/src/fmc_alias_csr.rs
> +    idevid_csr.rs
fixed

2025-01-10 22:51 UTC, rusty1968 commented on drivers/Cargo.toml
> +fmc-alias-csr = []
removed

2025-01-13 23:24 UTC, mhatrevi commented on fmc/src/flow/fmc_alias_csr.rs
> +fn write_csr_to_peristent_storage(env: &mut FmcEnv, csr: &FmcAliasCsr) -> CaliptraResult<()> {
Yes, but don't change the ROM code with this change. We can change it in 2.0.

2025-01-16 22:06 UTC, rusty1968 commented on common/src/lib.rs
> +pub const RUNTIME_SIZE: u32 = 96 * 1024;
FMC size increased.

2025-01-16 22:08 UTC, rusty1968 commented on drivers/src/persistent.rs
>              );
done

2025-01-16 22:09 UTC, rusty1968 commented on runtime/src/main.rs
> +const BANNER: &str = r#"Caliptra RT"#;
Can we keep this change optional, so we can merge this PR?

2025-01-16 22:09 UTC, rusty1968 commented on drivers/src/persistent.rs
> +    pub fmc_alias_csr: FmcAliasCsr,
Feature was removed.

2025-01-20 17:03 UTC, nquarton commented on drivers/src/persistent.rs
> +pub const RESERVED_MEMORY_SIZE: u32 = 18 * 1024;
Is this where the 1kB comes from for the runtime size change from 97 to 96kB?

2025-01-20 17:32 UTC, nquarton commented on runtime/src/get_fmc_alias_csr.rs
> +            0 => Err(CaliptraError::RUNTIME_GET_FMC_CSR_UNSUPPORTED_FMC),
Are we guaranteed to get a 0 for the length on an older FMC that does not support this? Is there no issue with the FMC and RT using different persistent memory maps?

2025-01-20 17:36 UTC, nquarton commented on runtime/tests/runtime_integration_tests/test_data/fmc_alias_csr.txt
> +Certificate Request:
Will this need to be updated for any change in FMC?

2025-01-20 17:39 UTC, nquarton commented on runtime/tests/runtime_integration_tests/test_get_fmc_alias_csr.rs
> +fn test_missing_csr() {
I'm missing how this is related to the FMC alias CSR. Was this a copy-paste that didn't get updated?

2025-01-20 18:03 UTC, rusty1968 commented on runtime/src/get_fmc_alias_csr.rs
> +            0 => Err(CaliptraError::RUNTIME_GET_FMC_CSR_UNSUPPORTED_FMC),
Persistent memory map is not different. The offset for the FMC Alias CSR is carved out from what was previously reserved memory. DCCM is zeroed out during cold boot : https://github.com/chipsalliance/caliptra-sw/blob/main/rom/dev/src/start.S#L98

2025-01-20 18:32 UTC, rusty1968 commented on runtime/tests/runtime_integration_tests/test_data/fmc_alias_csr.txt
> +Certificate Request:
Yes, https://github.com/chipsalliance/caliptra-sw/tree/main/rom/dev#alias-fmc-dice-layer--pcr-extension

2025-01-20 18:34 UTC, rusty1968 commented on drivers/src/persistent.rs
> +pub const RESERVED_MEMORY_SIZE: u32 = 18 * 1024;
This is reserved memory in DCCM. FMC_SIZE is  related to ICCM. We had to add code size to implement the feature as well as carve out space in DCCM to store the CSR.

2025-01-20 18:37 UTC, nquarton commented on runtime/src/get_fmc_alias_csr.rs
> +            0 => Err(CaliptraError::RUNTIME_GET_FMC_CSR_UNSUPPORTED_FMC),
Okay, just wanted to make sure it was guaranteed to be 0. Thanks!

2025-01-20 19:18 UTC, nquarton commented on runtime/tests/runtime_integration_tests/test_data/fmc_alias_csr.txt
> +Certificate Request:
Is there a defined way to update them? The smoke test has similar test data that can be updated by uncommenting some lines in the test and running it. For some reason I am having trouble finding where these files are actually read in and used in the testing though.

2025-01-22 17:30 UTC, nquarton approved these changes

2025-01-28 00:45 UTC, mhatrevi commented on runtime/src/main.rs
> +const BANNER: &str = r#"Caliptra RT"#;
Keep these strings as is. Increase the RT size if needed.

2025-01-28 20:22 UTC, rusty1968 commented on runtime/src/main.rs
> +const BANNER: &str = r#"Caliptra RT"#;
Hi, Vishal. Perhaps I should give you some context : this FMC and RT are competing for ICCM as a resource. This new feature required FMC size increase. I can't increase RT size without taking from the FMC. I need to find space somewhere.

2025-01-29 17:12 UTC, clundin25 commented on runtime/src/get_fmc_alias_csr.rs
> +            _ => Err(CaliptraError::RUNTIME_INTERNAL),
nit: Is this dead code? I think the len case before this will catch everything.

2025-01-29 17:14 UTC, clundin25 approved these changes

2025-01-29 17:17 UTC, clundin25 commented on runtime/src/get_fmc_alias_csr.rs
> +                // size of the buffer in `GetIdevCsrResp`
nit: s/GetIdevCsrResp/GetFmcAliasCsrResp/

2025-01-30 02:17 UTC, mhatrevi approved these changes

2025-01-30 20:52 UTC, merged