[fix] KAT fixes
chipsalliance/caliptra-sw pull request #40
Opened 2023-03-13 00:00 UTC by mhatrevi

Change contains few fixes to the KAT library.

2023-03-13 10:44 UTC, vsonims requested changes

2023-03-13 10:44 UTC, vsonims commented on kat/src/ecc384_kat.rs
>          let priv_key = Array4xN([
Can we make all Array4xN constants. specifically the one within methods that have expected value. This is taking up lot of code space. Consts get promoted readonly sections where as for let bindings the compiler is generating store instructions to the stack.

2023-03-14 18:36 UTC, vsonims submitted a review, later dismissed

2023-03-15 15:18 UTC, vsonims approved these changes

2023-03-15 17:12 UTC, JohnTraverAmd approved these changes

2023-03-15 18:17 UTC, vsonims approved these changes

2023-03-15 18:21 UTC, merged