Update caliptra-rtl submodule to the latest main
chipsalliance/caliptra-sw pull request #417
Opened 2023-06-23 00:01 UTC by korran

2023-06-26 17:17 UTC, jlmahowa-amd approved these changes, later dismissed

2023-06-29 17:00 UTC, mhatrevi requested changes

2023-06-29 17:02 UTC, korran commented on kat/src/sha384acc_kat.rs
We can't remove this, as there will be a race condition where the sha_acc engine is open for SoC use between drop() being called and report_error().

2023-06-29 17:05 UTC, korran commented on kat/src/sha384acc_kat.rs
IMHO We probably need to drop this in both cases (so you can unlock it at some well-controlled time later), but that will break the tests as that other unlock code doesn't exist yet.

2023-06-29 17:05 UTC, mhatrevi commented on kat/src/sha384acc_kat.rs
Fine, we'll double lock (or check if it is already locked and not lock) in report_error.

2023-06-29 17:06 UTC, korran commented on kat/src/sha384acc_kat.rs
You need to do that anyways. report_error() can be called early in startup while the peripheral is already locked.

2023-06-29 17:14 UTC, mhatrevi approved these changes

2023-06-29 18:26 UTC, merged