[feat] Add Memory Layout Module
chipsalliance/caliptra-sw pull request #460
Opened 2023-07-06 16:37 UTC by ajisaxena

This PR resolved the following:-

1. Makes the linker script simpler by removing the variables needed by the code. 
2. One place to have all the memory related variables. 
3. Added test cases such that invalid variables are caught as part of unit testing. 
4. At many occasions it was observed the data structure was bigger than the size of memory reserved for it. Since all the memory related variables are in single module, it is easier to catch these type of issues in unit test.

2023-07-06 20:24 UTC, rusty1968 submitted a review, later dismissed

2023-07-06 22:00 UTC, mhatrevi requested changes

2023-07-06 23:52 UTC, ajisaxena commented on rom/dev/src/fuse.rs
> +        core::slice::from_raw_parts_mut(ptr, FUSE_LOG_SIZE)
Yea, I was planning to have the size as number of entries but missed it.

2023-07-07 00:03 UTC, ajisaxena commented on rom/dev/src/flow/cold_reset/mod.rs
> +                let tbs_max_size = FMCALIAS_TBS_SIZE as *const u8 as usize;
Updated.

2023-07-07 00:03 UTC, ajisaxena commented on rom/dev/src/fuse.rs
> +        core::slice::from_raw_parts_mut(ptr, FUSE_LOG_SIZE)
Updated.

2023-07-07 00:03 UTC, ajisaxena commented on rom/dev/src/pcr.rs
> +        core::slice::from_raw_parts_mut(ptr, PCR_LOG_SIZE)
Updated

2023-07-07 00:03 UTC, ajisaxena commented on common/src/memory_layout.rs
> +    assert!((MAN2_ORG - MAN1_ORG) as usize >= core::mem::size_of::<ImageManifest>());
Updated

2023-07-07 00:03 UTC, ajisaxena commented on common/src/memory_layout.rs
> +    if MAN1_SIZE != MAN2_SIZE {
Updated

2023-07-07 00:15 UTC, mhatrevi approved these changes

2023-07-07 00:16 UTC, rusty1968 approved these changes

2023-07-10 17:12 UTC, rusty1968 commented
Can this be merged now?

2023-07-10 21:13 UTC, jhand2 approved these changes

2023-07-10 21:38 UTC, merged