Do not write LDevID or FMC alias public keys to DV slots.
chipsalliance/caliptra-sw pull request #478
Opened 2023-07-15 16:35 UTC by bluegate010

These are unnecessary, and this change frees up DV slots for future use by FMC.

2023-07-18 03:34 UTC, rusty1968 commented
This PR does quite a bit more than what its summary describes.

2023-07-18 03:55 UTC, bluegate010 commented
> This PR does quite a bit more than what its summary describes.

Ack, have amended the description with the knock-on changes.

2023-07-18 09:45 UTC, vsonims requested changes

2023-07-18 09:45 UTC, vsonims commented on rom/dev/README.md
> -| 2 | | | 🔒LDevID Cert Signature R |
How do we generate cert chains without pub key. I want to make sure all content generated by ROM that is critical for the Caliptra IP to function correctly without depending on DCCM. This change violates this design principle

2023-08-07 20:10 UTC, bluegate010 commented
Closing as not necessarily needed for now.

2023-08-07 20:10 UTC, closed without merging