Rename constructor for error type
chipsalliance/caliptra-sw pull request #647
Opened 2023-08-16 06:51 UTC by sphinxc0re

Since there is no need to differentiate between a const-time constructor and a runtime constructor, the `_const` suffix seems redundant.

2023-08-16 18:05 UTC, jhand2 submitted a review, later dismissed
LGTM. Will merge when conflicts are resolved.

2023-08-17 18:15 UTC, jhand2 approved these changes

2023-08-17 18:55 UTC, korran requested changes
The problem is that CaliptraError::new() will panic if the value is zero. I really want to discourage people from calling it from firmware; it should only be used from const contexts.

Instead, code that wants to create a CaliptraError from a u32 should use TryFrom (with unwrap if it doesn't care about panics). Apprently that commit has not gone in yet; here's the PR:

https://github.com/chipsalliance/caliptra-sw/pull/655

2023-08-22 06:58 UTC, sphinxc0re commented
Fair enough. Will close this in favor of #655

2023-08-22 06:58 UTC, closed without merging